#!/bin/bash
echo starting
sleep 2s

make CC=clang ARCH=arm64 O=out olive_defconfig
make CC=clang ARCH=arm4 O=out -j16 \
        HEADER_ARCH=arm64
        SUBARCH=arm64
        CXX=c++
     NM=llvm-nm \
     OBJCOPY=llvm-objcopy \ 
     OBJDUMP=llvm-objdump \
     STRIP=llvm-strip
         CROSS_COMPILE=aarch64-linux-gnu- \
         CROSS_COMPILE_ARM32=arm-linux-gnueabi-